### ISSUE TITLE
Don't use discrete GPU on MacBook Pro with 2 GPUs

### ISSUE THREAD

**Issue by mathiaswagner** [ttscoff/nv#175]
I figured out that nvalt triggered the use of the discrete (Nvidia) GPU on my MacBook Pro 2010.
I added

```
<key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
```

to the _Info.plist_ file in the app package and now it seems to work fine. There is some doc available [here](https://developer.apple.com/library/mac/#qa/qa1734/_index.html)

**Comment by nicseow** [comment]
nvALT 2.2b (111) was constantly triggering the discrete gpu (upon launch) on a macbook pro retina 2012 with 10.12 sierra – it wasn't ever an issue with el cap. adding the line suggested by mathiaswagner in the first post to info.plist did the trick.
