### ISSUE TITLE
Clarification of SimpleNote sync preferences warning

### ISSUE THREAD

**Issue by josh-nz** [ttscoff/nv#207]
In the preferences for nvALT, on the Notes tab, there is a warning:

Note contents will be delivered as clear text.
Notes >400k in size may have issues with sync.

Can you explain these two points a little more? According to SimpleNote, data is encrypted during network transport (ie, https). Is this not the case from nvALT for some reason?

Is the 400k the size of an individual note, in kilobytes, or number of characters, words? Or is it a total of > 400,000 notes, regardless of the size or length of each note?

Thanks.

**Comment by troy** [comment]
I ran into this and also just finished reading `SimplenoteSession` to confirm it was encrypted. 
I think many, probably most, people will read "delivered as" and think that it refers to on-the-wire encryption, not data-at-rest encryption.

How about changing the wording to:

> Warning: Note contents will be encrypted during transmission with HTTPS, but stored in clear text. Notes >400k ..
