### ISSUE TITLE
Preview using Marked...

### ISSUE THREAD

**Issue by nancikennedy** [ttscoff/nv#291]
The menu option "Preview using Marked" does not work with Marked 2. While the "Preview" Menu flashes black with the key combo, nvALT behaves like the option was never selected. Same with manually selecting from the menu. It took me a moment before I realized that's likely because Marked 2 is newer, but in case it's not and that option is supposed to work properly....here's a post to that effect. 

-nanci
p.s. On MacBook Pro, running Mavericks, with latest version of nvALT and Marked 2.

**Comment by shamrt** [comment]
Hi Brett,

I am experiencing this problem, having just purchased Marked 2 (former Marked user). I've dicked around, trying various things, but to no avail; e.g., I've reinstalled both applications as well as run `open -b com.brettterpstra.marky [MD file]`. The latter, by the way, returns `LSGetApplicationForInfo() failed with error -10814 while trying to determine the application with bundle identifier com.brettterpstra.marky.`.

I'm running NVAlt Version 2.2b (111), Marked 2 Version 2.4.9 (875), and the latest version of Mavericks.

Thank-you for any guidance you can provide.

**Comment by ttscoff** [comment]
The app name is now "Marked 2" and bundle id is com.brettterpstra.marked2. Public release of nvALT isn't caught up yet. 

Note that you can just drag a folder containing nvALT text notes to marked and it will show the most recently edited one, keeping up as you switch notes. 

This is my iPhone. There are many like it, but this one is mine.
