### ISSUE TITLE
Bug in documentation around template.html

### ISSUE THREAD

**Issue by Jaffa** [ttscoff/nv#293]
The [Customization](http://brettterpstra.com/projects/nvalt/#custom) section of the nvALT homepage says:

> After the first time you run the Preview window, look in `~/Library/Application Support/Notational Velocity` and you’ll find two files: `template.html` and `custom.css`.

This isn't accurate:
1. The directory is not created, nor auto-populated with `template.html` or `custom.css`
2. nvALT seems to only use `template.html` if put in `~/Library/Application Support/nvALT`

**Comment by jaapsoft** [comment]
On Mac OSX 10.7.5  ~/Library/Application Support/nvALT  is empty and in  ~/Library/Application Support/Notational Velocity I find two files: template.html and custom.css.

**Comment by arolle** [comment]
In c79f6cca6757e4669a2b7061d8c9b994ba7a3bf9 it says:

    no longer writing custom css and template to disk

You can put your template (e.g. `https://github.com/ttscoff/nv/blob/master/template.html`) to `~/Library/Application Support/nvALT`. Works for me with version 2.2b (111).

**Comment by cplr** [comment]
as a new user of nvALT this confused me. I'm considering adding a button in the preferences to copy these files for you to the right location (and then perhaps open the folder in Finder) - would this be a good pull request?

**Comment by cplr** [comment]
https://github.com/ttscoff/nv/pull/485
