### ISSUE TITLE
Notes List stuck on _Loading Notes..._

### ISSUE THREAD

**Issue by BrendanThompson** [ttscoff/nv#337]
The Notes List is stuck on _Loading Notes..._, I have tried removing nvALT to no avail. I have also tried disabling the __Simplenote__ sync which just seems to come back every time i start the app again. Any ideas on resolving this?

**Comment by ttscoff** [comment]
This is usually the result of a bad character in a note, and often only 
solved by moving all of the notes out of the folder, then adding them 
back until the problem one is detected.
