### ISSUE TITLE
Nvalt 2 keeps getting stuck when i load a long note

### ISSUE THREAD

**Issue by Metamba** [ttscoff/nv#338]
I have this long text file in plain text but with several special characters. Anytime I try to load the file on Yosemite and preview it, the app crashes. I have had to return to Notational Velocity till the bug is sorted out.

**Comment by ianmorty** [comment]
It might be the markdown processor itself crashing - take a look at activity monitor and see if something like `multimarkdown` is pegged at 100%.

**Comment by Metamba** [comment]
The CPU usage of multi markdown is hovering around 99.8%. Any solution in sight?

Doyin Olusunmade 




On Tue, May 19, 2015 at 7:17 AM -0700, "Ian Mortimer" <notifications@github.com> wrote:












It might be the markdown processor itself crashing - take a look at activity monitor and see if something like multimarkdown is pegged at 100%.

**Comment by ianmorty** [comment]
not really an nvAlt issue as it's a third party component bundled with nvAlt (@ttscoff will have to pull me up here).  There are a couple of things you can do to work around it:

1. run the file through a `multimarkdown` processor and find out what the offending character or string is causing the issue and remove it
2. update the `multimarkdown` processor used by nvAlt

**Comment by Metamba** [comment]
Can you please guide me through applying the solutions? Thank you.

**Comment by ttscoff** [comment]
Update the multimarkdown binary in the app package.

Get the binary here http://fletcherpenney.net/multimarkdown/download/

Copy /usr/local/bin/multimarkdown over the file at 
/Applications/nvALT.app/Contents/Resources/multimarkdown

There's still an update coming with the newer version, but that should 
fix some errors for you.

**Comment by ianmorty** [comment]
For option 2, you could try following [these instructions](https://fletcher.github.io/MultiMarkdown-4/installation) to install a different `multimarkdown` and then place the binary in this location `~/Library/Application Support/MultiMarkdown` and nvAlt should pick it up.  You should also probably figure out why your file is causing issues with the processor - put it through an online markdown validator or run it through your freshly installed version of multimarkdown from the step above.  Consult the formatting guides [here](https://daringfireball.net/projects/markdown/syntax) for true Gruber markdown or the [penny fletcher extensions](http://fletcherpenney.net/multimarkdown/) to markdown

**Comment by ianmorty** [comment]
@ttscoff beat me to it

**Comment by Metamba** [comment]
Installing the new multimarkdown solved it for me. Thanks for the awesome support.
