### ISSUE TITLE
⌥ ⌘ V - Paste Markdown Link

### ISSUE THREAD

**Issue by doty-e9data** [ttscoff/nv#348]
nvALT version 2.2b

Expected behavior:
When a link is on the clipboard pressing ⌥ ⌘ V  should result in:
```
[](http://brettterpstra.com/projects/nvalt/)
```

Behavior I am seeing:
When a link is on the clipboard pressing ⌥ ⌘ V results in:
```
[]: http://brettterpstra.com/projects/nvalt/
```

When I preview, there is no link or text showing.

**Comment by maclm** [comment]
To get an inline link (first behaviour), you have to select the text to be enclosed in brackets first.
Without any text selected, you get a reference link (second behaviour).
This is actually a feature, among others, but I can't find at the moment where I've seen this explained.
If I find, I'll post the source here.

**Comment by doty-e9data** [comment]
Thank you for your prompt and thorough reply.

**Comment by doty-e9data** [comment]
Thank you for the prompt and thorough reply.  I can confirm the behavior that you describe.  Now that I understand the feature I am again amazed by your project.  It is a nice subtlety.

**Comment by maclm** [comment]
Well, for one thing, this is for sure not _my_ project.
Glad I could help you though.
