### ISSUE TITLE
Images being listed among notes

### ISSUE THREAD

**Issue by 0xroy** [ttscoff/nv#357]
Hi !

I have recently noticed that some of my pictures were listed on nvalt. They are `.png` `.jpg` files and I _never_ added their extension or filetype to nvalt's filter (attachment).

<img width="363" alt="capture d ecran 2015-11-29 a 14 44 06" src="https://cloud.githubusercontent.com/assets/10902805/11457389/b502db4c-96a7-11e5-9b3b-1ba9c9f2d098.png">

<img width="233" alt="capture d ecran 2015-11-29 a 10 18 27" src="https://cloud.githubusercontent.com/assets/10902805/11457392/cccb2cac-96a7-11e5-8bde-fa03851c2aec.png">

If I select the "image note" by accident, nvalt wont respond and I must kill its task. Nvalt is also REALLY slow to launch (like 30-45 seconds).  
Last screenshot : 

<img width="586" alt="capture d ecran 2015-11-29 a 14 48 07" src="https://cloud.githubusercontent.com/assets/10902805/11457411/64963b94-96a8-11e5-811b-ee4b6155870d.png">

**Comment by maclm** [comment]
Interresting.
I've always kept my image files in a subfolder and never seen this issue.
Maybe it is a solution, since nvALT doesn't index subfolders.

**Comment by ttscoff** [comment]
The images shouldn't be read. I would suggest backing up your notes 
(ensure they're stored as plain text files and just copy the folder), 
deleting the "Notes & Settings" file, and letting nvALT create a new 
index.

-Brett

**Comment by roylockhart** [comment]
Worked like a charm ! Thanks @ttscoff :)
