### ISSUE TITLE
Keyboard Maestro + nvALT

### ISSUE THREAD

**Issue by heshca** [ttscoff/nv#359]
I'm running into issues with a Keyboard Maestro macro being unable to function within nvALT and only nvALT. I've [sought support](https://forum.keyboardmaestro.com/t/insert-text-by-pasting-not-working-in-nvalt/2601) on the KM forums and it seems that others aren't running into the same problem as me. 

Essentially KM isn't recognizing the typed string that should trigger an "Insert Text by Pasting" function. The string triggers the KM macro in every other piece of software I've tried it in (Mellel, Chrome, Pages, Safari, Stickies, etc...). nvALT is the only place it isn't working. I have the most up-to-date nvALT version 2.2b (111).

**Comment by ttscoff** [comment]
Do you have encryption turned on in preferences?

If that's not the issue, please post to 
https://github.com/ttscoff/nv/issues.

Thanks,
Brett

**Comment by heshca** [comment]
Brett,

No, I don't have encryption turned on. I do, however, have "Secure Text Entry" enabled, which I must have skimmed over when troubleshooting earlier. Everything is working fine now.

Best,
Christopher
