### ISSUE TITLE
nvALT 2.2 (120) "Internal Error" (uncaught exception) when entering fifth character of Tag

### ISSUE THREAD

**Issue by georgeogoodman** [ttscoff/nv#375]
macOS Sierra 10.12.1 Beta (16B2327e)
nvALT 2.2 (120)

1. start nvALT
2. select any item in the list
3. add a Tag (either by clicking on the Tag column entry for the item or via keyboard shortcut or via File-Tag)
4. when one types the fifth character of the new tag, nvALT throws this exception

Note that if one selects "Continue" there's no sign (after adding and modifying multiple items) of any ongoing issue in the application.

See crash report (attached) and screen clip (attached)

[nvALT 2.2 (120) "Internal Error" (uncaught exception) when entering fifth character of Tag.txt](https://github.com/ttscoff/nv/files/491207/nvALT.2.2.120.Internal.Error.uncaught.exception.when.entering.fifth.character.of.Tag.txt)

<img width="798" alt="screenshot 2016-09-24 08 38 23" src="https://cloud.githubusercontent.com/assets/22415993/18809522/7396962c-8232-11e6-9b14-f43388ab2898.png">

**Comment by ttscoff** [comment]
Confirmed, we'll need to look into this.

**Comment by elasticthreads** [comment]
Pretty sure this is fixed in the latest update. Please let us know back here if you still have issues editing tags.

**Comment by georgeogoodman** [comment]
Hi,

Sad to say that the uncaught exception remains and occurs when I enter 
the fifth character of a new (not pre-existing tag) AND ALSO if I edit 
an existing tag (adding a character to an existing tag even if that 
character does not make the tag a five-or-more character tag).

I am running nvALT 2.2 (120) -- see attached screen clip -- and when I 
click nvALT-Check for Updates... the app informs me I'm up-to-date.

george g.
-- 
george o. goodman
+1503-512-9103

**Comment by ttscoff** [comment]
120 is not the latest update. See http://brettterpstra.com/2016/09/27/nvalt-2-dot-2-take-2-dot-2-one-more-time-with-feeling/

-Brett

**Comment by georgeogoodman** [comment]
Thanks, Brett. I hadn't caught the newest blog post. 121 in place and 
all is well!

george g.
-- 
george o. goodman
+1503-512-9103



> Brett Terpstra <mailto:notifications@github.com>
> September 28, 2016 at 7:22 AM
> 120 is not the latest update. See 
> http://brettterpstra.com/2016/09/27/nvalt-2-dot-2-take-2-dot-2-one-more-time-with-feeling/
>
> -Brett
>
> On Sep 28, 2016, 9:11 AM -0500, georgeogoodman
