### ISSUE TITLE
2.2(120) crash with paste in new note

### ISSUE THREAD

**Issue by bonnefoi** [ttscoff/nv#378]
Create a new note, paste some text -> crashed.

**Comment by tantramar** [comment]
Ditto. macOS Sierra. Happens repeatedly. Revealing the blank note in the Finder — the name gets saved — and pasting in the contents of the note using BBEdit results in a note that then opens happily in nvALT.

**Comment by kevwil** [comment]
Same crash happening here, on El Capitan

**Comment by adsahay** [comment]
Same here. This is a major bug - I've tried `Cmd+V` and `Edit -> Paste` with same results. I'm on El Capitan.
