### ISSUE TITLE
nvALT 2.2 (120) on OS X 10.11.6 - how to avoid crashes until fixed.

### ISSUE THREAD

**Issue by ericsw** [ttscoff/nv#381]
A [comment](http://disq.us/p/1c95nxm) by Tony on the [OK, nvALT 2.2 take 2](http://brettterpstra.com/2016/09/23/ok-nvalt-2-dot-2-take-2/) blog post noted that moving nvALT.app out of the Applications folder fixed his problems. I placed my copy in my home folder and everything is working (tagging, pasting in new notes, typing, etc.) without crashing at the moment. Until a new version is pushed out, you may want to do the same.

edit - It seems that quitting nvALT and reopening the application in the same location causes the crashes to happen again. Moving locations before starting the app seems to avoid the crashes.

edit 2 - new day, and now nonstop crashes. I give up and am going back to v2.2 (110) and staying on 10.11.5 until this is fixed

**Comment by ttscoff** [comment]
I'm thinking it must be related to this: http://lapcatsoftware.com/articles/app-translocation.html

It seems there are still other bugs involving tagging and anything that links to libcrypto, but the launch issue could be explained by this. The way to test would be to [download directly](http://abyss.designheresy.com/nvALT2.2120.zip), unzip, move the app to /Applications in Finder, then launch with a double click from the app folder. If anyone can try this out, please let me know if it helps. (This should only affect Sierra users.)

**Comment by alanfluff** [comment]
Running Sierra, I did per above and found:

- opening in Finder with double-click then type in a record is AOK
- opening via Alfred by invoking Alfred and typing nv then type in a record is AOK
- opening via Alfred using an Alfred key sequence then type in a record results in crash.

**Comment by ptcox** [comment]
Direct download, moving to Applications, double-click launch => works fine.
Launch via LaunchBar => crashes again, as soon as I try to edit. And now double-click launch also crashes on edit.

**Comment by alanfluff** [comment]
> And now double-click launch also crashes on edit.
Though I'm sure I tested:
> opening via Alfred by invoking Alfred and typing nv then type in a record is AOK
multiple times and it consistently worked, now it's failing. Odd.

**Comment by ericsw** [comment]
Bummer, Quitting and reopening nvALT causes the crashes to happen again. I'm still on 10.11.6 so I don't know if/how app translation is affecting me. Moving application locations each time after quitting seems to work though. Let me know if I can provide anything for troubleshooting.

**Comment by EricFromCanada** [comment]
On 10.11.6 and downloaded directly and double-clicked from Finder multiple times. Sometimes it would allow editing fine, sometimes it would crash on the first keypress, and sometimes on the second.

**Comment by speciale** [comment]
On 10.12 (16A323) nvALT was working fine till… this morning. Id did downloaded the zip but I can't edit my notes.
In logs appears like this

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]

If I can help in anyway (testing I mean), I'll will do it gladly

**Comment by RobertAKARobin** [comment]
Still using 10.11.6. Some weird occasional crashing since the update.

```
Process:               nvALT [7074]
Path:                  /Applications/nvALT 2.app/Contents/MacOS/nvALT
Identifier:            net.elasticthreads.nv
Version:               2.2 (120)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           nvALT [7074]
User ID:               1057751255

Date/Time:             2016-09-27 10:13:49.294 -0500
OS Version:            Mac OS X 10.11.6 (15G1004)
Report Version:        11
Anonymous UUID:        28D0C247-4302-3522-C8AE-F2D4F0D90188

Sleep/Wake UUID:       AC178F9C-D4B9-4C2C-8A03-687CF2C00E94

Time Awake Since Boot: 66000 seconds
Time Since Wake:       5400 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(paste:) from sender NSMenuItem 0x7f81187377a0
```

**Comment by ericsw** [comment]
Yeah today nvALT is now crashing no matter what. That is some strange set of bugs you got going on there, what with the time based and location based crashing and all. Here, have some logs that may be of use (or not. we got spin dumps, system log selections, and crash logs.). I'm heading back to v2.2 (110) and staying on 10.11.6 until this gets fixed. [BitWriter](http://brettterpstra.com/2015/09/14/an-nvalt-and-more-status-report/), you cannot come fast enough for me.
