### ISSUE TITLE
Unable to change notes folder

### ISSUE THREAD

**Issue by growdigital** [ttscoff/nv#382]
I installed nvALT using `brew cask install` after updating my Mac to 10.11.6. It worked fine, and then I tried to manually replace the `Notational Data` folder in `~/Library/Application Support/` from a backup, trashing the existing folder. This error message came up:
```
Unable to initialize notes database in 
~/.Trash/Notational Data because the file wasn't found.
Please choose a different folder in which to store your notes.
```
Now I can't choose a different folder in `Preferences > Notes`, it just defaults to `<Directory unknown>`.

I've tried reinstalling after `brew cask zap nvalt` to get rid of any existing preferences but no joy, so I can't get back to a clean install. 

Screengrabs attached. Thanks, Jake
![01-initial-error](https://cloud.githubusercontent.com/assets/1061992/18847319/ab9c7352-8421-11e6-803f-eb0066d470fb.png)![02-notes-prefs-options-locked](https://cloud.githubusercontent.com/assets/1061992/18847318/ab98ceaa-8421-11e6-8897-03d44a38fff7.png)

PS nvALT is The Bomb btw :)

**Comment by elasticthreads** [comment]
I'm sorry this happened to you.
Can you try the following and report back:
1. Quit nvALT if its running.
2. Back up any existing notes folder you have.
3. Open Terminal.app
4. Run the following command between the double quotes: "'defaults delete net.elasticthreads.nv'"
5. Run the following command (substituting <yourhomefolder>) between the double quotes: "rm -rf '/Users/<yourhomefolder>/Library/Application Support/Notational Data/'" 
6. Run the following command (substituting <yourhomefolder>) between the double quotes: "rm -rf '/Users/<yourhomefolder>/Library/Caches/net.elasticthreads.nv'" 
7. Launch nvALT

This should run as though first launch. With your notes in a single database at ~/Library/Application Support/Notational Data/

From there you should be able to choose a new notes folder.

**Comment by elasticthreads** [comment]
Also:
The most recent update was released yesterday, September 30. Download it at the link below as auto-updating might not work between some earlier releases and this one (though it should work going forward):
http://brettterpstra.com/projects/nvalt/

The newest version is: 2.2 (122)  please make sure you're using that before trying my fix above.

**Comment by growdigital** [comment]
Brilliant, that works a treat. Very glad to have nvALT back up and running :)

**Comment by Magurius** [comment]
Sorry for the delay, elasticthreads
I followed your advice and restored my default note folder.
Thanks for this fantastic and great app!
