### ISSUE TITLE
download location for homebrew cask

### ISSUE THREAD

**Issue by msridhar** [ttscoff/nv#386]
I wanted to update the version of nvALT in Homebrew Cask to 2.2b121.  Here is the current cask file:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/nvalt.rb

The file points at `abyss.designheresy.com` as a download location for 2.2b120, but the 2.2b121 DMG has not been posted there yet.  Is there a new plan as far as the official download location of nvALT?  Or is this still being worked out?  Totally understand if this is still in flux.  I just thought it might be a bad experience for Homebrew Cask users if they install nvALT and then run into the crashes observed with 2.2b120.

**Comment by ttscoff** [comment]
Moved servers, and there's no "b" in the filename anymore: 
http://assets.brettterpstra.com/nvALT2.2121.dmg

-Brett

**Comment by msridhar** [comment]
Thanks!  Also, there is an `appcast` URL in the current cask file.  Is it right to assume that is not currently relevant and should be removed, due to the recent issues with Sparkle on Sierra?

**Comment by ttscoff** [comment]
That is correct, at least for the time being.

-Brett

**Comment by msridhar** [comment]
Thanks again!  I haven't submitted changes to Homebrew Cask before, so I'll leave this issue open until the PR is accepted, in case there are any further questions.
