### ISSUE TITLE
Smart quotes and dashes just won't die

### ISSUE THREAD

**Issue by arel** [ttscoff/nv#391]
Every time I restart nvALT after latest upgrades, smart quotes and dashes re-enable themselves (after turning them off in the `Edit > Substitutions > Show Substitutions` menu).

Is there a way to disable the feature _permanently_, or could the default at least be set to _off_ so "smart substitutions" do not get in the way of, e.g., writing markdown?
---

On version 2.2 (122).

**Comment by ttscoff** [comment]
I'll look into this. It's not something I've noticed because I have 
smart dashes/quotes disabled system-wide, and nvALT does respect that 
setting.

-Brett

**Comment by danburzo** [comment]
I'm not sure if this is bad form, but I just wanted to add a +1 for this, I'm experiencing the same issue.

**Comment by elasticthreads** [comment]
This is fixed for the next release. Thanks for the reports. All the substitution menu options should now work independently of any system wide settings. (please report back after the next update if this doesn't work or there are some bugs)

**Comment by elasticthreads** [comment]
This should be fixed in the updates we released this week. Whatever you set in the Edit>>Substitutions menu will now be permanently set just for nvALT.
