### ISSUE TITLE
The tab bar in the "Notes" preferences pane is hidden in nvALT 2.2 (122)

### ISSUE THREAD

**Issue by extracts** [ttscoff/nv#392]
The tab bar in the "Notes" preferences pane is clipped in nvALT 2.2 (122) so that you can merely see/click it. Here's a screenshot from v2.2 (122) (using the German localization):

![nvalt2 2 122](https://cloud.githubusercontent.com/assets/1410036/19071661/7b51c52e-8a31-11e6-8520-820a518a34d8.png)

As a result, the sync and security options aren't really visible/accessible anymore.

For comparison, here's the same preferences pane as shown by v2.2b (111):

![nvalt2 2b 111](https://cloud.githubusercontent.com/assets/1410036/19071678/9043ac22-8a31-11e6-8959-6ed4d67e2c65.png)

**Comment by elasticthreads** [comment]
This will be fixed in the next release.
Thanks for reporting the bug.
