### ISSUE TITLE
Note List Window is nowhere to be found

### ISSUE THREAD

**Issue by olivierthereaux** [ttscoff/nv#394]
Since upgrading to nvALT  2.2, my note list window - basically the main and only window for the app, has disappeared, and there is no way to conjure it back. 

I tried quitting and restarting (nope), tried changing the location of the notes database (nope - although the settings window does show up if I ask for it), reinstalling (still nope) and even deleting the Library/Application Support/nvALT folder (am on OSX 10.11.6).

Help? Anyone?

**Comment by elasticthreads** [comment]
Do you use the "Hide Dock Icon" preference? 
If yes: what happens when you click on its menubar icon? Or right-click on it and select "Search or Create"

If not: What happens when you switch to nvALT (by clicking on its dock icon)? What happens if you hit cmd-L when nvALT is active (even if there's no window, the menubar should change to nvALT's menus)?

**Comment by olivierthereaux** [comment]
@elasticthreads yes! that was helpful.

In more details: switching to nvALT and hitting cmd-L did the trick, showing the window at last.

If I quit nvALT and re-open it I still have to do the same thing again (unlike before, where the window would show up immediately). 

Maybe worth re-framing the issue as:

1. on the mac client, there should be a way to summon the main window from the "Window" menu. 
2. there seems to be a bug (?) where the main window does not appear on start

**Comment by elasticthreads** [comment]
@olivierthereaux Thanks for quick update.

1. Good point. In the meantime, if you prefer mouse + menu to keyboard: "Search or Create" from the Note menu will work. 
2. Will look into this.

quick question: when you don't have the window, does clicking on the dock icon bring it back?

**Comment by olivierthereaux** [comment]
@elasticthreads clicking on the dock icon does not, indeed, bring back the window if it is not present. (It does if window is merely minimised, of course.)

**Comment by olivierthereaux** [comment]
PS: I just tried `defaults delete net.elasticthreads.nv` and it solved the "window does not appear uby default any more" issue. 

Wish I'd had the reflex to keep a trace of what those defaults were before wiping them, but this may, hopefully, help resolve the bug.

**Comment by elasticthreads** [comment]
Improved some things in the next release. Please report back if you have anymore issues like this.

thanks.
