### ISSUE TITLE
Problem with (german) Preferences Panel

### ISSUE THREAD

**Issue by gstueck** [ttscoff/nv#396]
It is not possible to edit the simple note account
(nvalt 2.2 (122), OS X 10.11.6 german)

![bildschirmfoto 2016-10-08 um 23 21 31](https://cloud.githubusercontent.com/assets/1112416/19216015/4597e41a-8dae-11e6-84fa-7dafff95b53f.png)

**Comment by elasticthreads** [comment]
Thanks for the report. This is fixed in the next release (which should be out this week)
