### ISSUE TITLE
Can't close or interact with search / find box

### ISSUE THREAD

**Issue by n8henrie** [ttscoff/nv#398]
Version 2.2 (122)
OSX 10.12

If I search for text (`cmd F`) I am unable to click anything in the search box, including the `Done` box to close the box. Interestingly, if I copy text to the clipboard and hit `cmd F` again it puts the clipboard text into the search box, but I'm unable to interact with any of the other buttons or text fields.

![screen shot 2016-10-09 at 4 13 04 pm](https://cloud.githubusercontent.com/assets/1234956/19224079/4d18604c-8e3b-11e6-8e9e-603f3190d22f.jpg)

**Comment by elasticthreads** [comment]
Thanks for the report, this is fixed in the next release
