### ISSUE TITLE
Print to PDF freezes the program

### ISSUE THREAD

**Issue by EJFuchs** [ttscoff/nv#399]
I have created a note using md and when I try to print the preview to pdf, the print screen opens, but after selecting the option Save as PDF, the application hangs and needs to be force quitted to proceed. 
I have a macbook pro, running MacOS Sierra

**Comment by ttscoff** [comment]
I've heard this reported before, and pre-Sierra, but I'm not able to 
replicate it. Assuming you're running the latest nvALT (2.2 122), are 
you printing from the notes window or the preview?

-Brett

**Comment by EJFuchs** [comment]
I have the latest nvAlt. I was printing from the preview window.
The problem persists if you use the shortcut Cmd-Opt-Shift-P.   The application hangs as well.

Eric,

**Comment by ttscoff** [comment]
If you choose "Open in Preview" from the print dialog, does that work? 
Just trying to determine if it's hanging during the render or disk 
access parts. Also, does it hang before the Save dialog comes up, or 
after selecting a location and confirming the file save?

-Brett

**Comment by EJFuchs** [comment]
The steps are as follows:
1. Open nvALT and choose note to export
2. Use Cmd-Opt-Shift-P and print dialog opens
3. a. Select save as PDF from the drop-down menu (lower left corner of print dialog). Application hangs, no output is produced.
3. b. Select Open in Preview from the print dialog (lower left corner of print dialog). Application hangs, Preview opens but with a blank page.
3. c. Print to PDFWrite (virtual printer). The application hangs also, and a blank pdf is produced.

In all accounts the application freezes and the traffic light buttons do not work. Application needs to be forced quit. It appears to be a problem with rendering.

Let me know if you need more info.

eric,

**Comment by elasticthreads** [comment]
The updates we released this week should have fixed this. Please report back if it didn't. Thanks.
