### ISSUE TITLE
2.2.6 (124) changes Bring-to-Front behavior in way that tempts data loss

### ISSUE THREAD

**Issue by gouch** [ttscoff/nv#411]
Previously, triggering the Bring-to-Front shortcut (correctly) focused the search field. This meant you could trigger nvALT and begin typing your search immediately.

The latest release instead keeps focus inside a note, maintaining whatever text selection was last active. This means when you trigger bring-to-front and start typing your search, you instead type over the content of a note.

**Comment by ttscoff** [comment]
I'm seeing this as well and think it's worth fixing. I'll look into it.

-Brett

**Comment by Zortrium** [comment]
This change is driving me batty.  Reverting to the old behavior would be greatly appreciated.

**Comment by philrj** [comment]
Such a relief I'm not the only one. Accidentally adding bits of text everywhere and deleting sections of selected text from previous copy/paste. Been going crazy and probably annoying neighbors w/shouts of expletives at 3am. Def eager for fix or toggle to switch behavior.

**Comment by volt4ire** [comment]
Where can I download a previous version of nvALT without this bug?

**Comment by Zortrium** [comment]
I reverted to a backup.  This issue makes the current version a non-starter.  I'm frankly surprised that more people aren't commenting here -- the whole point of nvALT in my workflow is to save time by quickly jumping to the appropriate note using bring-to-front then search (keyboard only).  Using the newest I'm forced to use the mouse to reselect the search bar each and every time.

**Comment by ttscoff** [comment]
Version 2.2b106 http://abyss.designheresy.com/nvaltb/nvalt2.2b106.zip

The bug you're referring to is already fixed and will be out in an 
update today or tomorrow.

**Comment by ttscoff** [comment]
Or you can just hit ⌘L.

**Comment by Zortrium** [comment]
Never bothered to learn that shortcut.  Thanks!

**Comment by gouch** [comment]
Thank you @ttscoff
