### ISSUE TITLE
Feature Request: Option to Use Custom Preview App?

### ISSUE THREAD

**Issue by strawhead** [ttscoff/nv#418]
Just as Command+Shift+E lets me open the note in the editor of my choice, could a similar keyboard shortcut give an option to preview in the app of my choice? Ideally both the build in preview and the optional preview would be available with different keyboard shortcuts.

**Comment by elasticthreads** [comment]
I doubt we'll add the ability to set a custom markdown preview app like you're requesting (we're not adding major features these days, mostly bug fixes). But already you can use Brett's app, Marked. ctrl-cmd-m  (look in the Preview menu)

**Comment by strawhead** [comment]
Fair enough. And Marked suits my needs just fine. Can't believe I didn't notice that before. Thanks!
