### ISSUE TITLE
Auto complete of links has just started to fail

### ISSUE THREAD

**Issue by sdonovan1985** [ttscoff/nv#434]
Occationally, autocomplete does not work. That is, when I type "[[a" I expect a bunch of my notes starting with "a" to populate a list. 

What I've seen of the behaviour: When I first start nvALT, it will work on whatever note is up, but clicking a link to get to another note and it stops working (no autocomplete for links). I restart, works on first page, then doesn't.

Something that may be coincidental: I installed the OSX 10.12.2 update today.

I use plain text files for storage. Size of "Notational Data" folder:
1,651,066 bytes (2.1 MB on disk) for 172 items
Version 2.2.7 (125)

**Comment by sdonovan1985** [comment]
This may have been a result of an update. After a few reboots and an update cycle later, all is working. 

Probably can be ignored. Closing.

**Comment by brentshermana** [comment]
#320 
In my experience, this is still an issue. @sdonovan1985 please consider reopening!

**Comment by sdonovan1985** [comment]
I have experienced it once since then, and it seemed to be related to an update of WordService from DEVONtechnologies. A reboot or two usually fixed it.
