### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by pol** [ttscoff/nv#452]
There have been no commits to this repo since May of 2015 (nearly two years ago), but the last updates to NVAlt2 came via auto-update in November.  The post by @ttscoff indicated that they were [working on a tool called BitWriter](http://brettterpstra.com/2016/09/22/nvalt-2-dot-2-bugfixes-sierra-compatibility/), which will presumably be a non-OSS app (as I don't see a public repo for the development).   I am assuming that's why there have been no more commits to this public repo, as they are reserving their work for BitWriter. 

I have no issue with making a product out of this, but can we at least get the latest code for NVAlt committed to this repo so we (as a community) can continue to work on it?

**Comment by ttscoff** [comment]
One should always check the branches. https://github.com/ttscoff/nv/tree/2.2.5

**Comment by pol** [comment]
I apologize!  I assumed the list of commits was global, not branch-specific!  It doesn't help that the branch is labeled "2.2.5" and not "2.2.7", but I totally understand.  

Thanks for the correction.

**Comment by niklas-heer** [comment]
The last commit on all branches was a year ago? Is it still alive?

Just curious because I really like! 😄

**Comment by amarendra** [comment]
@niklas-heer It seems so. I settled on this after trying multiple note apps (and nv was crashing a lot). I think I will stick to the open source https://github.com/Automattic/simplenote-macos (I use the iOS app anyway). Problem is it doesn't let you store/access local note texts and the interface leaves a lot to to be desired.
