### ISSUE TITLE
Missing hotkey, preview and sync++ at the same time

### ISSUE THREAD

**Issue by torbjornlunde** [ttscoff/nv#458]
### Problems
- Bring-to-Front Hotkey stops working
- nvALT appears blank before interacting with it and after previews in the list are (mostly) absent
- Editing features such as tag autocomplete and insert link shortcut does not work
- SimpleNote sync doesn‘t work (it doesn‘t sync)

I think these are connected since when I **always get all these problems together**.

I do know what triggers it. If I remember correctly this is something I found when I have come back to my laptop (2-3 times now).

Uninstalling nvALT using AppCleaner then reinstalling fixes all these problems (untill they appear again). So I suspect there is something that is cached or retained somehow that has a part in causing this.

### More on the hotkey
- nvALT does not appear anymore when using my asssigned hotkey (in my case case ⌃⌥Space)  or clicking the dock icon
- Clicking Window →  Show Main Window after clicking the dock does work
- As does the keyboard shortcut assosciated with that command (⌘⇧N)
- Same with menu bar icon
- When I do get nvALT to appear again (more bellow) the hotkey does not hide nvALT either
- Reassigning the key fixes thie hotkey-issue as long as the app is running. The problem returns when the app is restarted (regardless of which key combination I used)

### More on the missing notes and preview
- When the window first appear it looks completely blank (see attached screenshot)
- If I focus the omnibar and hit escape I get a list of my notes 
- Except that all the notes are missing preview (see attached screenshot)
- If I create a new note this one *does* feature a preview in the list (see attached screenshot)

### Other stuff
- The insert link shortcut (⌘⇧L) does not work anymore (nothing happens).
- Tag autocomplete is missing
- It does not sync to SimpleNote at all anymore in any direction

### My setup:
- macOS Sierra 10.12.5
	- Running on a 2011 MacBook Air
- nvALT 2.2 (126)
	- I sync with SimpleNote
	- I use a Single Database (stored locally, no Dropbox or anything)

### Screenshots

Initial view
![initial-view](https://user-images.githubusercontent.com/1179046/27379995-c13a5fec-567d-11e7-8863-c4a4d41f9668.png)

After hitting esc
![no-note-previews](https://user-images.githubusercontent.com/1179046/27379994-c13a432c-567d-11e7-8449-36c2b6b421bd.png)

After a note have been created
![after-note-created](https://user-images.githubusercontent.com/1179046/27379993-c118215c-567d-11e7-9648-0e66a6417875.png)

**Comment by ryanfitzer** [comment]
I second this behavior. This is triggered when restarting the app.

> If I create a new note this one does feature a preview in the list (see attached screenshot)

You can also make the preview show by toggling the Notes List with ⇧⌘C.

**My setup**:

- macOS Sierra 10.12.3
- MacBook Pro (Retina, 15-inch, Mid 2014)
- nvALT version 2.2 (122)
- Dropbox sync

**Comment by moderntimesmedia** [comment]
I'm running into this problem now, but on High Sierra. Possibly related, as I just upgraded. Here's the specifics:

- opening the app does not show anything until you choose Window -> Show Main Window
- initial the screen is empty
- Hiding/showing note previews, and/or changing layout from/to vertical seems to solve this.
- renaming a note makes it disappear from the list, and it doesn't seem to actually rename
    - furthermore, I appear to get stuck in the rename input field
- shutting down the app is really show (beachball slow)

**Comment by torbjornlunde** [comment]
Upgrading to High Sierra actually fixed this problem for me (on both macs).
