### ISSUE TITLE
Save new files as .md

### ISSUE THREAD

**Issue by timwis** [ttscoff/nv#497]
Hi folks, it seems nvALT is saving new notes as `.txt` instead of `.md`. Is there a way to have them saved as `.md`?

The settings window doesn't seem to have an option for how it saves new notes.

<img width="367" alt="screen shot 2018-02-24 at 10 26 19" src="https://user-images.githubusercontent.com/761444/36631894-4a0a4494-194d-11e8-9aab-4b8b3a9c0dfb.png">

**Comment by ttscoff** [comment]
Click the checkmark (☑️) box to set md as default. It's currently 
**txt** as indicated by the boldface on that line.

-Brett

**Comment by timwis** [comment]
Oh, wow, that worked. Er, a bit tucked away there, but did the trick. Thanks.
