### ISSUE TITLE
nvAlt 2.2.8 stopped working in OS X El Capitan (10.11.6)

### ISSUE THREAD

**Issue by agmarrugo** [ttscoff/nv#508]
I recently updated nvAlt to 2.2.8 on a machine that still has OS X 10.11.6. While the app still launches and I can see the menu, I cannot see the application window/pane.

**Comment by ttscoff** [comment]
I'd recommend trashing prefs and starting clean, but if you'd rather just revert, here's a link to 2.2.7: <http://abyss.designheresy.com/nvalt/nvALT2.2.7126.dmg>
