### ISSUE TITLE
Can't sync notes to a new folder

### ISSUE THREAD

**Issue by nitinsavant** [ttscoff/nv#557]
I sync my notes to Dropbox. I recently renamed the root folder from "Dropbox (Personal)" to "Dropbox", and the change seems to have broken my nvALT configuration folder sync, and I can't change it.

Here's a short video of what happens: https://youtu.be/stOu_bdG3g0

**Comment by bookcasey** [comment]
For anyone else experiencing this issue, a quick fix is to delete the preferences file: `~/Library/Preferences/net.elasticthreads.nv.plist`(or update it)

**Comment by BillKeenan** [comment]
and then open and close, to create a new plist, then open again. worked for me.
