### ISSUE TITLE
Various misbehaviors in Mojave

### ISSUE THREAD

**Issue by Matthias-Ferber-Cantina** [ttscoff/nv#565]
I'm seeing a number of strange behaviors since I upgraded to Mojave, more or less. (I've turned on Full Disk Access for nvALT already.) Is anybody else seeing any of these?

* At startup, neither the main window nor the preview is visible even though the app is foregrounded. I have to open it from the Window menu.
* When the main window appears, it's empty. I have to press a key to start a search before the notes are shown.
* The assigned hotkey is not working. (EDIT: it started working after I set it again, using the same key combination.)
* The Bookmarks menu is broken: it just shows the placeholder grayed-out "Item".
* When I delete a note, in the confirmation prompt, neither the Delete nor Cancel button dismisses the prompt, and I have to quit the app to continue. (It does do the deletion if I click Delete, though.)

I've scanned the list of issues and haven't seen anything similar — apologies if I missed something though.

**Comment by Matthias-Ferber-Cantina** [comment]
Closing this issue. It turned out to be caused by some kind of corruption in the preferences file; when I located the right file and deleted it, nvALT went back to normal.

**Comment by jacobweber** [comment]
Same exact things happened to me. I noticed that in the bad preferences file, the `Bookmarks` section had an extra empty dict at the end:
```
	<key>Bookmarks</key>
	<array>
		<dict>
			<key>NoteUUIDString</key>
			<string>A7ACD798-8899-40BD-9A9B-64F94DE0BC18</string>
			<key>SearchString</key>
			<string></string>
		</dict>
		<dict>
			<key>NoteUUIDString</key>
			<string>63E5AF7D-AB95-4756-831D-5A6C8B45DC85</string>
			<key>SearchString</key>
			<string></string>
		</dict>
		<dict>
			<key>NoteUUIDString</key>
			<string>0762DA2D-9114-41B4-BE91-58DDF1171FDB</string>
			<key>SearchString</key>
			<string></string>
		</dict>
		<dict/>
	</array>
```
Removing the empty dict fixed it.

**Comment by volt4ire** [comment]
@Matthias-Ferber-Cantina @jacobweber do you know where the preference file you mention is located? I'm having the same issue but can't find an nvalt preference file for it with that syntax. Thanks!

**Comment by Matthias-Ferber-Cantina** [comment]
@volt4ire I'm away from home without my laptop today, but I'm making a note to get back to you when I get home tomorrow, if@jacobweber hasn't come through yet. I think it was inside the ~/Library/Containers hierarchy (or whatever the correct path is to  the Containers directory).

**Comment by jacobweber** [comment]
@volt4ire @Matthias-Ferber-Cantina Looks like it's `~/Library/Preferences/net.elasticthreads.nv.plist`.
