### ISSUE TITLE
Unable to download client

### ISSUE THREAD

**Issue by built2order** [ttscoff/nv#582]
The links referenced in both this repo and on your website to download the app no longer resolve.

**Download Link**
* https://updates.designheresy.com/nvalt/nvALT2.2.8128.dmg

**Error**
This site can’t be reachedCheck if there is a typo in updates.designheresy.com.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ttscoff** [comment]
Link works fine for me, just tested.

**Comment by built2order** [comment]
And just like that, it's fixed...
