### ISSUE TITLE
Building on M1 (Apple Silicon)

### ISSUE THREAD

**Issue by n8henrie** [ttscoff/nv#585]
I wanted to see if I could build nvAlt to run natively on arm64 / Apple Silicon.

As a hobbyist it took a bit of work, and it doesn't look pretty, but I eventually got something that build and runs: <https://github.com/n8henrie/nv>

It seems like @ttscoff is (understandably) focused on nvUltra at this point, but I thought I'd drop a link to my fork in case any others were interested in the same (since the first thing I did was search issues for a few relevant M1 buzzwords).

**Comment by ttscoff** [comment]
This is great, thanks for sharing! (Haven't tested, but good to know it exists)

-Brett
